language: python
cache: pip

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.1"
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<2.3"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.1"
   - python: "2.7"
     env: DJANGO="django>=2.1,<2.2"
   - python: "2.7"
     env: DJANGO="django>=2.2,<2.3"

branches:
  only:
    - master

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jshint
  - jshint ./openwisp_users/static/openwisp-users/js/*.js

# command to install requirements
install:
  - pip install $DJANGO
  - python setup.py -q develop

# command to run tests, e.g. python setup.py test
script:
  - |
      if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then
        openwisp-utils-qa-checks \
          --migrations-to-ignore 2 \
          --migration-path \
            "./openwisp_users/migrations \
            ./tests/testapp/migrations" \
          --migration-module openwisp_users
      fi
  - coverage run --source=openwisp_users runtests.py

after_success:
  coveralls
