language: python
cache: pip

python:
  - "3.6"
  - "3.7"

env:
  - DJANGO="django>=2.1,<2.2"
  - DJANGO="django>=2.2,<2.3"
  - DJANGO="django>=3.0,<3.1"

branches:
  only:
    - master

before_install:
  - pip install --no-cache-dir -U -r requirements-test.txt
  - npm install -g jshint

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - ./run-qa-checks
  - coverage run --source=openwisp_users runtests.py

after_success:
  coveralls
